### ISSUE TITLE
What happens if the `git log` output is very very long?

### ISSUE THREAD

**Issue by IonicaBizau** [tunnckoCore/parse-git-log#2]
I needed [to limit the `git log` count to `100`](https://github.com/IonicaBizau/git-stats-importer/blob/9e047bf676410f502ebee0f278c7dd2f584fe3a2/bin/git-stats-importer#L77) to avoid errors. Does this library handle this?

**Comment by tunnckoCore** [comment]
Mm i dont know, will check it.

**Comment by tunnckoCore** [comment]
@IonicaBizau looks like it does [shows full jonschlinkert/template history](https://github.com/jonschlinkert/template/commits/master?page=22), which is 22 pages.

It's interesting why count of the result array is 166248, but yea. :laughing: Actually that's normal, when i think. I also noticed that it not include "first commit". hm.

**Comment by IonicaBizau** [comment]
@tunnckoCore Yeah, when the repo has lot of commits, `exec` sends an error back. I finally ended up with using [`gitlog-parser`](https://github.com/yorkie/node-gitlog-parser) by @yorkie -- it parses commits one by one, from *any stream* (in my case `spawn("git", ["log"]).stdout`), so it's obvious is friendlier in terms of memory.

Thanks! :smile:
