### ISSUE TITLE
Commit message doesn't match the rest of the commit object

### ISSUE THREAD

**Issue by doowb** [tunnckoCore/parse-git-log#6]
When I run `git log --pretty="%h %d %s"` I see these messages with their commit hash:

```bash
9b81d29  (HEAD, tag: 3.0.0, master) 3.0.0
5583b11  add task
bab35eb  2.0.0
f7b0637  (tag: 2.0.0) refactor
c9c1335  (tag: 1.0.0) 1.0.0
32c4712  implementation
793cfa5  first commit
```

But this is the array that I get back:

```js
[ { commit: '9b81d29e78b283ae435137889c4b0b6dd4ee1026',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:14:08 2016 -0400' },
  { message: '3.0.0',
    commit: '5583b1163ccb188bfe04c03aeeeed015da7d24bb',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:13:42 2016 -0400' },
  { message: 'add task',
    commit: 'bab35ebc3431c0a744ec017ad80eab6d96ee9773',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:12:27 2016 -0400' },
  { message: '2.0.0',
    commit: 'f7b06372b9225b3854c0b1b27c3956f0d08fab41',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:12:14 2016 -0400' },
  { message: 'refactor',
    commit: 'c9c133564f3f563fcde21c49ee110a3f2a2e8249',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:06:57 2016 -0400' },
  { message: '1.0.0',
    commit: '32c4712f3d8aadfa9eb0ea2a36ee0c39b8e94dfe',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:06:38 2016 -0400' },
  { message: 'implementation',
    commit: '793cfa5db68794e5f77951f9e5abb4e9ef6cd41a',
    author: 'doowb <brian.woodward@gmail.com>',
    date: 'Tue Nov 1 11:02:59 2016 -0400' } ]
```

Notice that the first item doesn't have a commit message and that the rest of the messages are off by one. I didn't look into the code yet, but thought you might have a quick idea on the fix.

**Comment by tunnckoCore** [comment]
@doowb hi there, sorry for the delay. I'm just jumping around these thousands halloween issues (really hate that @greenkeeper bot). Still can handle all the issues, can't imagine how Jon is feeling :D 

Nevermind. Just seen your issue, sorry for the delay. It looks like a quick fix.

**Comment by tunnckoCore** [comment]
@doowb what you think about this https://github.com/tunnckoCore/parse-git-log/issues/5

**Comment by doowb** [comment]
@tunnckoCore I think streaming could be useful in some cases, but for my usecase, I needed to get all of the commit messages first, so the callback/promise api is easier to work with.

**Comment by tunnckoCore** [comment]
Okey, thanks for the feedback. I'll look i I can refactor it this night (cuz it is pretty outdated) and release v1 stable.

**Comment by tunnckoCore** [comment]
Can you try it from master (or upcoming v1). I believe it would be easy to use and be useful. It gives you more things than previous implementation.

It's not a problem to promisify it and i'm thinking to support this too. Possibly after v1 release.

**Comment by tunnckoCore** [comment]
@doowb hope this not adds too many deps for your case if it is simple. I just need more things and kind of flexibility.

**Comment by tunnckoCore** [comment]
@doowb maybe https://github.com/tunnckoCore/parse-git-log/commit/ee91c9924f3e10e66258c2be97252e9a8642bb36 would work for you :)

**Comment by tunnckoCore** [comment]
Hope this v0.2.1 (already publish ;] ) will work for you, if it isn't too much for your case (if it is simple). :)
