### ISSUE TITLE
This module literally exports a noop

### ISSUE THREAD

**Issue by IonicaBizau** [tunnckoCore/parse-git-log#7]
https://github.com/tunnckoCore/parse-git-log/blob/001bff98d818360a430830d08c88ce88a0ef53d6/index.js#L8-L12

What happened?

**Comment by tunnckoCore** [comment]
@IonicaBizau ;d;d yea, just started the refactor :D But was busy these days and forgot to push it. If you need it, you can temporary lock to 0.0.0 ;d

**Comment by IonicaBizau** [comment]
But you did publish this refactoring state on npm and you *potentially* broke some apps using it. :boom:

**Comment by tunnckoCore** [comment]
Yea, absolutely. It's my fault. Usually I don't do such things, or in very rare cases (maybe once a year, not sure). I just published it, cuz I thought I will finish it in next few hours and release v1 almost instantly when it is finished. But yea, more important thing in real life came.

Sorry again, if some1 using it.

**Comment by tunnckoCore** [comment]
I believe I'll be able to push promise impl. today.

**Comment by IonicaBizau** [comment]
Learning every day. :grin:

**Comment by tunnckoCore** [comment]
Yea ;d I just was felt asleep for few mins because the streams headaches currently lol. It seems I'm not in best form these days :laughing:

**Comment by tunnckoCore** [comment]
Oookey, my mind is clear after a coffee. ;d

Hope https://github.com/tunnckoCore/parse-git-log/commit/8b89b0a5cd9b73357c56f4ef4aa1454ada3d4c37 looks better now. Will publish v1 after the tests and better docs. :)
